name: 'Tessl Publish'
description: 'Publish tiles to Tessl API'
inputs:
  path:
    description: 'Path to the directory to bundle and publish'
  token:
    description: 'Tessl API token for authentication'
    required: true
  review:
    description: 'Enable skill review quality gate before publish'
    default: 'true'
  review-threshold:
    description: 'Minimum review score (0-100) required to pass'
    default: '50'
runs:
  using: 'composite'
  steps:
    - uses: oven-sh/setup-bun@v2
    - run: bun install --production --frozen-lockfile
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: bun ${{ github.action_path }}/src/main.ts "${{ inputs.path }}"
      shell: bash
      env:
        TESSL_API_TOKEN: ${{ inputs.token }}
        TESSL_REVIEW: ${{ inputs.review }}
        TESSL_REVIEW_THRESHOLD: ${{ inputs.review-threshold }}
