name: 'Tessl Publish'
description: 'Publish tiles to Tessl API'
inputs:
  path:
    description: 'Path to the directory to bundle and publish'
  token:
    description: 'Tessl API token for authentication'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: oven-sh/setup-bun@v2
    - run: bun install
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: bun ${{ github.action_path }}/src/main.ts "${{ inputs.path }}"
      shell: bash
      env:
        TESSL_API_TOKEN: ${{ inputs.token }}
